name: gerenciador
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  email_validator: ^3.0.0
  flutter:
    sdk: flutter
  sqflite: ^2.3.3+1
  flutter_mobx: ^2.2.1+1
  mobx: ^2.3.3+2
  provider: ^6.1.2

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
